version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: mattermost_db
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmpassword
      - POSTGRES_DB=mattermost
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  mattermost:
    image: mattermost/mattermost-prod-app:latest
    container_name: mattermost
    environment:
      # Set the site URL for Mattermost; adjust as needed
      - MATTERMOST_SERVICESETTINGS_SITEURL=http://localhost:8065
      # Configure database settings for Mattermost
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmpassword@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
      # Fix for email notification error - more comprehensive settings
      - MM_EMAILSETTINGS_SENDEMAILNOTIFICATIONS=false
      - MM_EMAILSETTINGS_ENABLESMTPAUTH=false
      - MM_EMAILSETTINGS_FEEDBACKEMAIL=no-reply@example.com
      - MM_EMAILSETTINGS_SMTPSERVER=mail.example.com
      - MM_EMAILSETTINGS_SMTPPORT=587
      - MM_EMAILSETTINGS_ENABLEPREVIEWMODEBANNER=false
      - MM_EMAILSETTINGS_SKIPSERVERCERTIFICATEVERIFICATION=true
      - MM_EMAILSETTINGS_CONNECTIONSECURITY=
      # Disable admin notifications about email
      - MM_EMAILSETTINGS_ENABLEEMAILBATCHING=false
      - MM_EMAILSETTINGS_ENABLESECURITYFIXALERT=false
      # Ensure SiteURL is properly set
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
      # Disable unnecessary notifications
      - MM_ANNOUNCEMENTSETTINGS_ADMINNOTICESENABLED=false
      - MM_ANNOUNCEMENTSETTINGS_USERNOTICESENABLED=false
    ports:
      - "8065:8065"
    depends_on:
      - postgres
    volumes:
      - mattermost_data:/mattermost/data
    restart: always

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - APP_NAME=Gitea
      - DOMAIN=code.example.com
      - SSH_DOMAIN=code.example.com
      - ROOT_URL=http://localhost:3000
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - gitea_data:/data
    restart: always

volumes:
  mattermost_data:
  gitea_data:
  postgres_data:
