version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: mattermost_db
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmpassword
      - POSTGRES_DB=mattermost
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  mattermost:
    image: mattermost/mattermost-prod-app:latest
    container_name: mattermost
    environment:
      # Set the site URL for Mattermost; adjust as needed
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
      # Configure database settings for Mattermost
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmpassword@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
    ports:
      - "8065:8065"
    depends_on:
      - postgres
    volumes:
      - mattermost_data:/mattermost/data
      - ./data/mattermost/config:/mattermost/config
    restart: always

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - APP_NAME=Gitea
      - DOMAIN=code.example.com
      - SSH_DOMAIN=code.example.com
      - ROOT_URL=http://localhost:3000
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - gitea_data:/data
    restart: always

volumes:
  mattermost_data:
  gitea_data:
  postgres_data:
